#source 'https://rubygems.org'

gem 'ezap_core', git: 'https://github.com/vs-de/ezap_core.git'
gem 'ezap_service', git: 'https://github.com/vs-de/ezap_service.git'
#gem 'ezap_core',  path: '../../../ezap_core'
#gem 'ezap_service', path: '../../../ezap_service'

